### ISSUE TITLE
Error: ZIP file not provided. Error related to update on macOS

### ISSUE THREAD

**Issue by joshirio** [vladimiry/email-securely-app#103]
I was running v2.2.1 and since a new update was releases it looks like it fails to download something related to auto update?
Error message at start-up:

```
Unhandled Promise Rejection
Error: ZIP file not provided: [
  {
    "url": "https://github.com/vladimiry/email-securely-app/releases/download/v2.3.0/email-securely-app-2.3.0-mac.dmg",
    "info": {
      "url": "email-securely-app-2.3.0-mac.dmg",
      "sha512": "SXJI/rp1gjvXLjFk9N99pKLWLBNLwd3UJBdWqp76we2DAzMHHtByaDlNdIInTcUlSQ5s0jAHsKzeTLCc51BjBg==",
      "size": 88879760
    }
  }
]
    at newError (/Applications/email-securely-app.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/src/index.ts:29:17)
    at MacUpdater.doDownloadUpdate (/Applications/email-securely-app.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:36:13)
    at MacUpdater.downloadUpdate (/Applications/email-securely-app.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:419:19)
    at /Applications/email-securely-app.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:382:49
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/Applications/email-securely-app.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/Applications/email-securely-app.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/Applications/email-securely-app.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Applications/email-securely-app.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Applications/email-securely-app.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Applications/email-securely-app.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Applications/email-securely-app.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Applications/email-securely-app.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Applications/email-securely-app.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
```

Haven't upgraded to 2.3.0 yet. Tested on macOS, not sure if this happens also on windows and linux, maybe I'll test this later.

**Comment by vladimiry** [comment]
Might be an occasional issue with github's infrastructure, it serves release files from S3 if I'm not wrong.

**Comment by vladimiry** [comment]
I confirm error occuring on macOS, no issue on Windows.

Looks like `electron-updater` for some reason [is trying to resolve a ZIP file](https://github.com/electron-userland/electron-builder/blob/9422251ec1535a9fded552940d021eb2ba4ffc4e/packages/electron-updater/src/MacUpdater.ts#L36) expecting it to be placed close to DMG one. Here is the respective long-standing unresolved issue https://github.com/electron-userland/electron-builder/issues/2199.

Shipping ZIP builds for macOS [is stopped](https://github.com/vladimiry/email-securely-app/commit/af0757ae30e6812216eeb361b46009642ff84588) since v2.0.0-beta.9 (Dec 7, 2018). So looks like `Error: ZIP file not provided` started occuring since that point.

If the upstream error https://github.com/electron-userland/electron-builder/issues/2199 won't be fixed soon, I will consider using own custom/patched `electron-updater` version or getting back meaningless ZIP file shipping. Until then I'd recommend disabling the `auto-update` feature on macOS in the app settings. Besides I will consider making `auto-update` feature disabled by deault with next app release as I expected it to be more reliable tool.

![stop-auto-update](https://user-images.githubusercontent.com/1560781/52177507-c730f280-27d2-11e9-8acb-5156095af669.gif)

**Comment by vladimiry** [comment]
I just manually changed version value in `latest-mac.yml` from `2.3.0` to `0.0.0` file trying to suppress the error and this hack seems to work, no error on app start.

**Comment by vladimiry** [comment]
[v2.3.1](https://github.com/vladimiry/email-securely-app/releases/tag/v2.3.1) doesn't throw the error.
