### ISSUE TITLE
MacOS Disable Close to Tray error

### ISSUE THREAD

**Issue by joshirio** [vladimiry/email-securely-app#76]
When the option "Close to tray" is disabled in the settings, the app throws the following error when it is reopened from the tray icon (or dock):

```
Unhandled Promise Rejection
Error: Object has been destroyed
    at Object.toPromise (/Applications/email-securely-app.app/Contents/Resources/app.asar/app/webpack:/src/electron-main/api/endpoints-builders/general.ts:83:30)
    at Generator.next (<anonymous>)
    at /Applications/email-securely-app.app/Contents/Resources/app.asar/node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Applications/email-securely-app.app/Contents/Resources/app.asar/node_modules/tslib/tslib.js:103:16)
    at a.from (/Applications/email-securely-app.app/Contents/Resources/app.asar/app/webpack:/src/electron-main/api/endpoints-builders/general.ts:82:13)
    at Object.toggleBrowserWindow (/Applications/email-securely-app.app/Contents/Resources/app.asar/app/webpack:/external "about-window":1:1)
    at setContextMenu (/Applications/email-securely-app.app/Contents/Resources/app.asar/app/webpack:/src/electron-main/tray.ts:9:10)
    at [object Object] (/Applications/email-securely-app.app/Contents/Resources/app.asar/app/webpack:/src/electron-main/tray.ts:18:19)
    at Generator.next (<anonymous>)
    at /Applications/email-securely-app.app/Contents/Resources/app.asar/node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Applications/email-securely-app.app/Contents/Resources/app.asar/node_modules/tslib/tslib.js:103:16)
    at [object Object] (/Applications/email-securely-app.app/Contents/Resources/app.asar/app/webpack:/src/electron-main/tray.ts:18:19)
```

Not really an issue because on macOS the "close to tray" option is usually not disabled because the app keeps running as shown in the dock, as default behaviour like most apps.

This could be solved by either disabling (hiding) the option in the settings or if the user disables it it should completely quit the app on window close.

Version 1.5.4, macOS 10.14.1

**Comment by vladimiry** [comment]
I confirm the issue is reproducible.

I tend to keep the same behavior as on windows and linux, so the goal is to make it work this way:

> if the user disables it it should completely quit the app on window close.

**Comment by vladimiry** [comment]
@joshirio can you try the [updated beta9](https://www.dropbox.com/sh/t8emnmv0g5ypahm/AADjhplGXInGsNUNAIeZ2nhra?dl=0&lst=) build?

**Comment by joshirio** [comment]
Works, thank you!

**Comment by vladimiry** [comment]
Thanks for confirming, a new release is going to be published soon.
