### ISSUE TITLE
Writing validation: Duplicate accounts identified. Duplicated logins: USER@protonmail.com

### ISSUE THREAD

**Issue by nil0x42** [vladimiry/email-securely-app#78]
If i remove an account, any future try to add it again fails with the following error:
`Writing validation: Duplicate accounts identified. Duplicated logins: USER@protonmail.com`
So the "user" key is probably not correctly purged from config after account removal.

----
```js
[2018-11-29 13:12:52.516] [error] emitted.error: {"index":0} Error: Writing validation: Duplicate accounts identified. Duplicated logins: USER@protonmail.com.
    at Store.<anonymous> (/opt/email-securely-app/resources/app.asar/node_modules/fs-json-store/private/store.js:229:35)
    at step (/opt/email-securely-app/resources/app.asar/node_modules/tslib/tslib.js:133:27)
    at Object.next (/opt/email-securely-app/resources/app.asar/node_modules/tslib/tslib.js:114:57)
    at fulfilled (/opt/email-securely-app/resources/app.asar/node_modules/tslib/tslib.js:104:62)

[2018-11-29 13:12:52.520] [error] [WEB] [reducers/errors] <angular> { message:
   'Writing validation: Duplicate accounts identified. Duplicated logins: USER@protonmail.com.',
  name: 'Error' }
```

**Comment by vladimiry** [comment]
Need more info on how to reproduce the described issue

![add-remove-add](https://user-images.githubusercontent.com/1560781/49231020-125d0c80-f402-11e8-93e4-a8d5bbc8d6fa.gif)

**Comment by vladimiry** [comment]
Closing as no additional information was provided.
