### ISSUE TITLE
[Unhandled Error] Error: Object has been destroyed

### ISSUE THREAD

**Issue by nil0x42** [vladimiry/email-securely-app#82]
Hi ! A window just appeared with this error message. Still, i didn't notice any disconnection but i prefer to report as this bug might produce other issues in different circumstances.

```node
Unhandled Error
Error: Object has been destroyed
    at WebContents.send (/opt/email-securely-app/resources/electron.asar/browser/api/web-contents.js:100:15)
    at SafeSubscriber._next (/opt/email-securely-app/resources/app.asar/node_modules/pubsub-to-stream-api/dist/index.js:62:29)
    at SafeSubscriber.__tryOrUnsub (/opt/email-securely-app/resources/app.asar/node_modules/rxjs/internal/Subscriber.js:209:16)
    at SafeSubscriber.next (/opt/email-securely-app/resources/app.asar/node_modules/rxjs/internal/Subscriber.js:147:22)
    at Subscriber._next (/opt/email-securely-app/resources/app.asar/node_modules/rxjs/internal/Subscriber.js:90:26)
    at Subscriber.next (/opt/email-securely-app/resources/app.asar/node_modules/rxjs/internal/Subscriber.js:67:18)
    at BehaviorSubject.Subject.next (/opt/email-securely-app/resources/app.asar/node_modules/rxjs/internal/Subject.js:60:25)
    at BehaviorSubject.next (/opt/email-securely-app/resources/app.asar/node_modules/rxjs/internal/BehaviorSubject.js:51:31)
    at Object.<anonymous> (/opt/email-securely-app/resources/app.asar/app/electron-main.js:1:31828)
    at Generator.next (<anonymous>)
```

**Comment by vladimiry** [comment]
Closing as no requested information has been provided.
